# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0002_pokersession_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
