# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_chronicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicles',
            name='text',
        ),
        migrations.AddField(
            model_name='pokersession',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chronicle.Chronicles'),
        ),
    ]
