# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0004_auto_20171020_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokersession',
            old_name='list',
            new_name='chronicles',
        ),
    ]
